### ISSUE TITLE
can't get sysl pixel to work... blank screen

### ISSUE THREAD

**Issue by lilmike** [SystemLogoff/lovePixel#3]
Hiya,

I'm writing a basic test program to try out sysl pixel + iffy, which helps manage spritesheets with metadata files. So I basically draw a chessboard out of pixel art chess tiles which fills the 128x128 screen, then use sysl pixel to upscale it to its max size. However, without sysl pixel it draws fine, though to a very small window. Once I enable sysl pixel, the window just shows as blank. I've made sure that I am putting my draw calls in between start and stop calls, but the screen remains stubbornly blank. Here is my main.lua, minus the image -- sorry, i don't have permission to distribute the image...

```
iffy = require("iffy")
sp = require("pixel")

function love.load()
    sp.current_cursor = 0
    sp.load()
    iffy.newAtlas("chessboard_1.png")
end

function love.update(dt) sp.update(dt) end

function love.draw()
    sp.start()
    -- Things are now scaled...
    local x = 0
    local y = 0
    for y = 0, 7, 1 do
        for x = 0, 7, 1 do
            if x % 2 == 0 and y % 2 == 0 then -- black
                iffy.drawSprite("black-square", x * 16, y * 16)
            elseif x % 2 == 1 and y % 2 == 0 then -- white (gray)
                iffy.drawSprite("white-square", x * 16, y * 16)
            elseif x % 2 == 0 and y % 2 == 1 then -- white (gray)
                iffy.drawSprite("white-square", x * 16, y * 16)
            elseif x % 2 == 1 and y % 2 == 1 then -- black
                iffy.drawSprite("black-square", x * 16, y * 16)
            else -- Something has gone horribly wrong...
                print(
                    "Error! The else was encountered in the draw loop. This should never happen!")
                love.event.quit()
            end
        end
    end
    sp.stop()
end

function love.keypressed(key) if key == "escape" then love.event.quit() end end

```

And my very basic conf.lua...

```
function love.conff(t)
    t.window.width = 128 -- Base Width that we scale up.
    t.window.height = 128 -- Base Height that we scale up.
    t.window.resizable = false -- Controled though allow_window_resize, set false in conf.
    t.window.minwidth = 128 -- Should match Width
    t.window.minheight = 128 -- Should match Height
    t.version = "11.4"
--    t.window.fullscreen = true
end
```

Thanks for any help,

-Michael.

Here is a screenshot, if that helps...

![chessscreen](https://github.com/sysl-dev/Sysl-Pixel/assets/1117427/0fe20a54-9b86-4173-972e-20acaac6c128)

**Comment by sysl-dev** [comment]
Hey, I don't get the same issue when using the standard love draw commands. Could you take a look at the iffy library to see if it's using it's own canvas for drawing?

**Comment by lilmike** [comment]
Hiya,

I could not find the search term "Canvas" or "canvas" in the iffy code,
so I don't believe it does.

-Michael.





On Fri, Jul 14, 2023 at 04:34:00PM -0700, C.Hall wrote:
>Hey, I don't get the same issue when using the standard love draw commands. Could you take a look at the iffy library to see if it's using it's own canvas for drawing?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/sysl-dev/Sysl-Pixel/issues/3#issuecomment-1636557518
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my supernatural...
stationary bicycle

**Comment by sysl-dev** [comment]
[IffyTest.zip](https://github.com/sysl-dev/Sysl-Pixel/files/12065305/IffyTest.zip)

I can confirm that this test with iffy works on my machine.

With SYSL-Pixel Library: 
![image](https://github.com/sysl-dev/Sysl-Pixel/assets/13181256/0a67b91e-187c-4110-8790-456211b6daf1)

Without:
![image](https://github.com/sysl-dev/Sysl-Pixel/assets/13181256/f817dd64-01b6-4fe0-a062-a2dc93f88753)
